- src/main/java/com/bugsnag/Configuration.java
- src/main/java/com/bugsnag/Metrics.java
- src/main/java/com/bugsnag/Notification.java
- src/main/java/com/bugsnag/http/HttpClient.java
- src/test/java/com/bugsnag/http/HttpClientTest.java
I was toying with a Bugsnag logback appender which was calling client.notify inside the synchronized append method. Thread dump showed one thread stuck in `int status = conn.getResponseCode();` inside HttpClient, and a few hundred threads waiting for it to release the lock it was holding.
Apparently if not configured, the connect and read timeouts are infinite. I added 60s defaults and tried to make them configurable. Let me know what you think.
> Add configurable connection and read timeouts

- src/main/java/com/bugsnag/Configuration.java
- src/main/java/com/bugsnag/http/HttpClient.java
- src/test/java/com/bugsnag/http/HttpClientTest.java
Allowing the httpClient to use a proxy to send notifications to the bugsnag API.
> Bugsnag httpclient allow set proxy

- README.md
- src/main/java/com/bugsnag/Configuration.java
Changes the default to SSL in line with other notifiers and highlights the ability to change it in the documentation.
> Use SSL by default for communications with Bugsnag.com

- CONTRIBUTING.md
- src/main/java/com/bugsnag/utils/JSONUtils.java
- src/test/java/com/bugsnag/utils/JSONUtilsTest.java
Truncate very long payloads which will get rejected by Bugsnag with a 400 response.
Long values from the payload are limited in length and the string "[TRUNCATED]" is appended.  This is the same strategy used by the Bugsnag Ruby notifier - see:
https://github.com/bugsnag/bugsnag-ruby/blob/eb782074fa127bb6ede77f31347672f65591489c/lib/bugsnag/helpers.rb#L16
> Truncate very long payloads

- README.md
- src/main/java/com/bugsnag/Client.java
- src/main/java/com/bugsnag/Configuration.java
- src/main/java/com/bugsnag/Notification.java
- src/main/java/com/bugsnag/NotificationWorker.java
Adds a thread pool with 2 daemon worker threads that allow the notification to Bugsnag to occur asynchronously. Notifications are queued if the worker threads are busy.
Async notification is turned on by default but synchronous notification can be used using the `setAsynchronousNotification` method
> Added a thread pool to allow asynchronous notification to Bugsnag

- examples/simple/src/main/java/com/bugsnag/example/simple/ExampleApp.java
- src/main/java/com/bugsnag/delivery/AsyncHttpDelivery.java
The executor used by AsyncHttpDelivery indefinitely blocks application exit unless a shutdown is manually triggered. This replaces the executor with one which times out when idle and so doesn't block an exit.
cc @bullmo
> Stop AsyncHttpDelivery from indefinitely blocking exit

- examples/spring-web/README.md
- examples/spring-web/build.gradle
- examples/spring-web/src/main/java/com/bugsnag/example/spring/web/Application.java
- examples/spring-web/src/main/java/com/bugsnag/example/spring/web/ApplicationRestController.java
- examples/spring-web/src/main/java/com/bugsnag/example/spring/web/Config.java
- examples/spring-web/src/main/resources/application.properties
- examples/spring/README.md
- examples/spring/build.gradle
- examples/spring/src/main/java/com/bugsnag/example/spring/cli/Application.java
- examples/spring/src/main/java/com/bugsnag/example/spring/cli/ApplicationCommandLineRunner.java
- examples/spring/src/main/java/com/bugsnag/example/spring/cli/Config.java
- examples/spring/src/main/resources/application.properties
- settings.gradle
- src/main/java/com/bugsnag/Bugsnag.java
- src/main/java/com/bugsnag/delivery/AsyncHttpDelivery.java
- src/main/java/com/bugsnag/delivery/Delivery.java
- src/main/java/com/bugsnag/delivery/OutputStreamDelivery.java
- src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java
- src/test/java/com/bugsnag/BugsnagTest.java
- Add Spring boot example app.
- Add Spring boot web based example app.
- Add `close` method to Bugsnag to ensure it tears down connections (this is automatically called by Spring when tearing down the bean).
- Change the simple example to use `close` rather than `Shutdown`.
> Add Spring example apps

- CONTRIBUTING.md
- `signing.secretKeyRingFile` must be absolute path to home.
- Should use `--console=plain` when doing the release so we can read all the interactive instructions properly.
> Improved release instructions

- src/main/java/com/bugsnag/serialization/Serializer.java
Due to the horrors of Java dependency management, if you are using a version of jackson-databind pre 2.6, you will get `NoSuchMethodError`s in Bugsnag due to a method being renamed. If we use the deprecated method rather than the newly renamed one we can support both old and new versions of Jackson.
> Use deprecated method to ensure we don't break with older versions of jackson

- .travis.yml
Updates the CI configuration to add oracle JDK 9 and remove OpenJDK 6 and 7. OpenJDK 6 is no longer available, and OpenJDK 7 [fails with build errors while trying to load the gradle wrapper](https://travis-ci.org/bugsnag/bugsnag-java/jobs/277737848#L459).
> Use job matrix for builds, update JDK versions

- build.gradle
- examples/servlet/build.gradle
- src/main/java/com/bugsnag/callbacks/ServletCallback.java
- src/test/java/com/bugsnag/ServletCallbackTest.java
Given a report generated like so and captured from a servlet context:
```java
Report report = bugsnag.buildReport(exception);
report.setContext("custom context");
bugsnag.notify(report);
```
The context in the final report should retain "custom context" and not be overridden by callbacks.
> Allow overriding context set by servlet callback

- .travis.yml
- build.gradle
- release.gradle
* Replace missing SunEC in openJDK7 builds (works around https://github.com/gradle/gradle/issues/2421, fixes CI)
* Use android flavor of guava for JDK7 support (fixes class loading)
Fixes #65
> fix: Restore JDK7 support

- src/main/java/com/bugsnag/Configuration.java
- src/main/java/com/bugsnag/callbacks/DeviceCallback.java
Caches device metadata during initialization to avoid spawning hella threads.
To reproduce:
* Launch example spring app
* `curl http://localhost:8080/send-unhandled-exception` maybe 300 times :D 
* Observe the number of threads (in a profiler or otherwise)
> Cache hostname at launch

- src/main/java/com/bugsnag/util/FilteredMap.java
- src/test/java/com/bugsnag/util/FilteredMapTest.java
After upgrading to version 3.1.5, we noticed the following error:
```
com.bugsnag.delivery.SyncHttpDelivery    : Error not reported to Bugsnag - exception when serializing payload
com.bugsnag.serialization.SerializationException: Exception during serialization
at com.bugsnag.serialization.Serializer.writeToStream(Serializer.java:36) ~[bugsnag-3.1.5.jar:na]
at com.bugsnag.delivery.SyncHttpDelivery.deliver(SyncHttpDelivery.java:57) ~[bugsnag-3.1.5.jar:na]
at com.bugsnag.delivery.AsyncHttpDelivery$2.run(AsyncHttpDelivery.java:71) [bugsnag-3.1.5.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
at java.lang.Thread.run(Thread.java:748) …
```
> Make preemptive copy of map filtering specified keys

- src/main/java/com/bugsnag/Exception.java
- src/main/java/com/bugsnag/Report.java
- src/test/java/com/bugsnag/ExceptionTest.java
Allows users to override the exception name by calling `report.setExceptionName()`
N.B. this is only supported for the top-level exception, and not any Throwable causes (as the top-level class is the important bit which shows in the dashboard).
Addresses #72
> Add setter for overriding error class

- src/test/java/com/bugsnag/ThreadStateTest.java
Adds test coverage for serialisation of `ThreadState` name and stacktrace.
> Add coverage for serialisation of thread state properties

- build.gradle
- src/main/java/com/bugsnag/Bugsnag.java
- src/main/java/com/bugsnag/Configuration.java
- src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java
- src/test/java/com/bugsnag/ConfigurationTest.java
- src/test/java/com/bugsnag/SessionTrackerTest.java
Enables automatic session tracking by default.
`setEndpoints` API on configuration class.
- Auto capture enabled by default
- Deprecated `setEndpoint` and `setSessionEndpoint`
Added and ran unit tests, as per the design spec.
> Session tracking on by default

- CHANGELOG.md
- src/main/java/com/bugsnag/ThreadState.java
- src/test/java/com/bugsnag/ThreadStateTest.java
Captures the trace of `Thread.currentThread()`, which was previously omitted, and to identify it with a boolean flag in the serialised JSON.
- Alter `ThreadState` to stop removing the current thread from serialisation
- Conditionally write `errorReportingThread` boolean flag by checking thread ID
Added unit tests for general ThreadState serialisation, and for checking that the current thread is now captured.
> Capture trace of error reporting thread and identify with boolean flag

- CHANGELOG.md
- src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java
HttpUrlConnection may be null if the URL is malformed, or if a connection to the host could not be
opened. In this case `connection` will be null and no additional cleanup will be required.
Add null check in `finally` block if `connection` was not initialised.
> fix: add null check when disconnecting HttpUrlConnection

- CHANGELOG.md
- src/main/java/com/bugsnag/delivery/SyncHttpDelivery.java
Makes the constructors visible for `SyncHttpDelivery`, as per `AsyncHttpDelivery`. This allows external use of the synchronous delivery mechanism.
Made the `SyncHttpDelivery` constructor public and added a convenience zero-arg constructor.
Ensured that no compilation errors occurred in an example app with different package for all `Delivery` implementations.
Fixes #96 
> Make constructors public for SyncHttpDelivery

- bugsnag-spring/build.gradle
- bugsnag-spring/src/test/java/com/bugsnag/NotifierTest.java
- bugsnag/build.gradle
- bugsnag/src/main/java/com/bugsnag/Notification.java
- bugsnag/src/main/java/com/bugsnag/Notifier.java
- bugsnag/src/main/java/com/bugsnag/NotifierUtils.java
- bugsnag/src/main/java/com/bugsnag/SessionPayload.java
- bugsnag/src/test/java/com/bugsnag/BugsnagTestUtils.java
- bugsnag/src/test/java/com/bugsnag/NotifierTest.java
Updates the Notifier name in error/session payloads if the notifier is bugsnag-spring.
Adds a `NotifierUtils` class which checks whether the `BugsnagSpringConfiguration` class is available on the classloader. This is a good proxy for determining whether the notifier is `bugsnag-spring` or `bugsnag-java`.
Added unit tests for serialisation, manual test of example plain/spring apps.
> Update notifier payload info

- CHANGELOG.md
- UPGRADING.md
This changeset adds a migration guide for moving a plain Java app to use the bugsnag-spring artifact. It also adds a changelog entry that briefly explains:
- Whether to use bugsnag-java or bugsnag-spring
- Links to upgrade steps/further documentation
- High-level summary of new functionality
> Add upgrade and changelog for Spring

- bugsnag/src/main/java/com/bugsnag/BugsnagAppender.java
- bugsnag/src/main/java/com/bugsnag/logback/BugsnagMarker.java
- bugsnag/src/test/java/com/bugsnag/AppenderMetaDataTest.java
- bugsnag/src/test/java/com/bugsnag/MarkerTest.java
- examples/logback/src/main/java/com/bugsnag/example/logback/cli/Application.java
- features/filtering_metadata.feature
- features/fixtures/scenarios/src/main/java/com/bugsnag/mazerunner/scenarios/LogbackMetaDataScenario.java
- features/meta_data.feature
Allow meta data to be added to individual logger statements via a custom marker object
Previously we used a custom exception, but using a marker is viewed as a slightly cleaner approach
> Add callbacks via markers

- bugsnag-spring/build.gradle
- bugsnag/build.gradle
- build.gradle
- examples/logback/build.gradle
- examples/servlet/build.gradle
- examples/simple/build.gradle
- examples/spring-web/build.gradle
- examples/spring/build.gradle
- features/fixtures/mazerunner/build.gradle
- features/fixtures/mazerunnerspringboot/build.gradle
Specifying `mavenCentral` as a repository in addition to `jcenter` makes it possible to perform a clean build of the project in the case where one provider suffers downtime.
> Specify maven central as a preferred repository over jcenter

- release.gradle
Allow a sources jar to be published to the local maven repository along with the library jar when executing `./gradlew publishToMavenLocal` which is useful for local testing and debugging.
> Allow sources to be published to mavenLocal()

- bugsnag-spring/src/main/java/com/bugsnag/BugsnagSpringConfiguration.java
- bugsnag-spring/src/main/java/com/bugsnag/ScheduledTaskBeanLocator.java
- bugsnag-spring/src/main/java/com/bugsnag/ScheduledTaskConfiguration.java
- bugsnag-spring/src/test/java/com/bugsnag/ScheduledTaskBeanLocatorTest.java
- bugsnag-spring/src/test/java/com/bugsnag/ScheduledTaskConfigurationTest.java
- features/fixtures/mazerunnerspringboot/src/main/java/com/bugsnag/mazerunner/scenarios/ScheduledTaskExecutorScenario.java
- features/fixtures/mazerunnerspringboot/src/main/java/com/bugsnag/mazerunnerspringboot/ScheduledTaskConfig.java
- features/fixtures/mazerunnerspringboot/src/main/java/com/bugsnag/mazerunnerspringboot/ScheduledTaskExecutorService.java
- features/scheduled_task_executor.feature
The Spring Notifier sets an `ErrorHandler` on the application's [`TaskScheduler`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/TaskScheduler.html), which is required to capture unhandled exceptions that occur in [scheduled tasks](https://spring.io/guides/gs/scheduling-tasks/). This is configured via a [`SchedulingConfigurer`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/SchedulingConfigurer.html) which is invoked on application startup.
Previously the notifier assumed that if the `taskRegistrar.getScheduler()` returned null, then no `TaskScheduler` was configured. The notifier therefore set a custom `TaskScheduler` with a bugsnag error handler, and a single-threaded `Executor`. However, …
> Support other methods of configuring a TaskScheduler

- CHANGELOG.md
- bugsnag-spring/src/main/java/com/bugsnag/ScheduledTaskBeanLocator.java
- bugsnag/src/main/java/com/bugsnag/Notifier.java
- gradle.properties
Remove the `@Configuration` annotation from `ScheduledTaskBeanLocator` which would prevent an application from starting if the class was imported into an application because a bean of that type is already explicitly defined in `BugsnagSpringConfiguration`.
> Remove unnecessary @Configuration annotation

- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/Report.java
- bugsnag/src/main/java/com/bugsnag/callbacks/DeviceCallback.java
Migrates non-standard device fields which are not specified in our [Error API docs](https://bugsnagerrorreportingapi.docs.apiary.io/#reference/0/notify/send-error-reports) to `metaData.device` instead.
- Migrated `osArch`, `runtimeName`, `runtimeVersion`, and `locale` to `metaData.device`.
- Deprecated `report.setAppInfo` and `report.setDeviceInfo` in favour of `report.addToTab`
Ran existing tests on CI, inspected payload manually to confirm that the JSON appears as expected, and confirmed that each field still shows on handled/unhandled errors in the dashboard.
> Migrate non-standard device fields to metaData.device

- bugsnag-spring/src/test/java/com/bugsnag/SpringMvcTest.java
- bugsnag-spring/src/test/java/com/bugsnag/TestUtils.java
- bugsnag/src/main/java/com/bugsnag/logback/BugsnagMarker.java
- bugsnag/src/test/java/com/bugsnag/MarkerTest.java
Workarounds for deprecation build warnings for `anymapof` and a deprecated method in `Marker` that we override.
> Fix build warnings

- common.gradle
- config/checkstyle/checkstyle.xml
- examples/logback/src/main/java/com/bugsnag/example/logback/cli/Application.java
- examples/servlet/src/main/java/com/bugsnag/example/servlet/ExampleServlet.java
- examples/spring-web/src/main/java/com/bugsnag/example/spring/web/ApplicationRestController.java
- examples/spring-web/src/main/java/com/bugsnag/example/spring/web/Config.java
- examples/spring/src/main/java/com/bugsnag/example/spring/cli/ApplicationCommandLineRunner.java
- examples/spring/src/main/java/com/bugsnag/example/spring/cli/Config.java
- settings.gradle
Upgrade checkstyle version to latest, 8.18, including removing a field from the checkstyle config that is no longer part of the schema. 
Also, tidy up import statements in the example projects.
> Upgrade checkstyle version + fix example imports

- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/Bugsnag.java
- bugsnag/src/main/java/com/bugsnag/delivery/AsyncHttpDelivery.java
- bugsnag/src/main/java/com/bugsnag/util/DaemonThreadFactory.java
Users have requested that we set the thread name in order to aid debugging.
Used a default thread factory and set the name on the created thread, throughout the bugsnag-java codebase.
Manually ran the example app and inspected the thread names in the debugger.
> Set thread name to aid debugging

- CHANGELOG.md
- bugsnag-spring/src/main/java/com/bugsnag/BugsnagSpringConfiguration.java
Not all users use Logback in their project, so `BugsnagSpringConfiguration` calling `BugsnagAppender` methods can throw a `NoClassDefFoundError`, as observed in #132. If the dependency is not on the classpath, we should ignore this error and continue initialising bugsnag as normal.
Ran the example app with [logback excluded](https://github.com/bugsnag/bugsnag-java/compare/log4j-example?expand=1), and confirmed that this change allowed the application to startup.
> Swallow Throwables thrown when configuring bugsnag appender

- CHANGELOG.md
- bugsnag-spring/src/main/java/com/bugsnag/BugsnagSpringConfiguration.java
- bugsnag-spring/src/main/java/com/bugsnag/SpringBootConfiguration.java
- bugsnag-spring/src/test/java/com/bugsnag/SpringMvcTest.java
- bugsnag/src/main/java/com/bugsnag/BeforeSendSession.java
- bugsnag/src/main/java/com/bugsnag/Bugsnag.java
- bugsnag/src/main/java/com/bugsnag/Diagnostics.java
- bugsnag/src/main/java/com/bugsnag/SessionTracker.java
- bugsnag/src/main/java/com/bugsnag/callbacks/DeviceCallback.java
- bugsnag/src/test/java/com/bugsnag/SessionPayloadTest.java
- features/meta_data.feature
- features/runtime_versions.feature
We should collect the following information in the `device.runtimeVersions` section of the payload:
- Java version
- Java type (runtime environment)
- Spring version
- Spring Boot version
- Moved `device.runtimeName` to `device.runtimeVersions.javaType`
- Moved `device.runtimeVersion` to `device.runtimeVersions.javaVersion`
- Moved `device.metaData.springVersion` to `device.runtimeVersions.springFramework`
- Moved `device.metaData.springBootVersion` to `device.runtimeVersions.springBoot`
- Added package-visible `BeforeSendSessions` callback which is invoked immediately before session delivery and allows mutation of the payload
- Added Spring/Spring Boot session callbacks that add runtime version info for sessions
Ran existing tests, and added new mazerunner scenarios to verify that …
> Migrate version information to device.runtimeVersions

- bugsnag/src/main/java/com/bugsnag/BugsnagAppender.java
- bugsnag/src/test/java/com/bugsnag/AppenderTest.java
This makes it possible to programatically create a Bugsnag logback appender without having to pass in the configuration options twice (once to the original client, and once again to the appender or defined in the logback XML file). This is especially useful if you are adding callbacks and configuration settings that are the same across the original instance and the Logback appender.
If the appender is created with an existing client, it is not possible to set any of the values of the appender that affect Bugsnag as it would also affect the original client.
Make it easier to share the configuration and callbacks between an existing Bugsnag client and a Bugsnag Logback appender.
This approach was taken to couple the logback and client configurations when both are used. This can be the case …
> Allow a BugsnagAppender to be created from an existing client.

- .travis.yml
- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/Configuration.java
- bugsnag/src/test/java/com/bugsnag/ConcurrentCallbackTest.java
If a callback is added while existing callbacks are being iterated through, bugsnag will crash. This
changeset addresses this issue by using a ConcurrentLinkedQueue which retains the callback order,
but will not crash if new callbacks are added concurrently. This fix has been ported from
https://github.com/bugsnag/bugsnag-android/pull/266
Added a unit test for regression testing, otherwise relied on existing coverage.
> Prevent potential ConcurrentModificationException when adding callback

- Gemfile
- features/async_method.feature
- features/fixtures/mazerunnerplainspring/Dockerfile
- features/fixtures/mazerunnerplainspring/src/main/java/com.bugsnag.mazerunnerplainspring/TestRestController.java
- features/meta_data.feature
- features/rest_controller.feature
- features/session_tracking_auto.feature
- features/steps/build_steps.rb
It appears that Tomcat 7.0 no longer has a ROOT webapp and so serves a 404 instead. This was being used by Mazerunner to check whether the app had started yet. However I believe it's more correct to check the deployed application rather than this placeholder app.
This changeset deploys the spring app to the root and amends the tests to run from the root.
A consequence of this is that the automatic session tracking tests are affected as each test starts by accessing a page and incrementing the counts. Therefore the scenario's expectation has been updated (and annotated) to expect a second count.
> test(mazerunner): fix failing tests for plain spring app due to tomcat root change

- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/Bugsnag.java
- bugsnag/src/main/java/com/bugsnag/util/DaemonThreadFactory.java
- bugsnag/src/test/java/com/bugsnag/DaemonThreadFactoryTest.java
- examples/simple/src/main/java/com/bugsnag/example/simple/ExampleApp.java
- features/fixtures/mazerunner/src/main/java/com/bugsnag/mazerunner/TestCaseRunner.java
The fix to prevent a resource leak in #143 improved the shutdown hook to prevent the resource leak (calling `ExceptionHandler.disable` and `config.delivery.close`) but also reverted the task scheduler from running as a daemon thread. Therefore, in a console app, or similar, which doesn't explicitly call `System.exit`, the JVM waits indefinitely for the `sessionExecutorService` to stop before triggering the shutdown hook.
This PR should be the benefits of both #143 and #121 to gracefully shutdown in both use cases.
Fixes #151 
* Reinstated the `DaemonThreadFactory` (removed in #143)
* Removed `System.exit` calls from the Spring Boot example as the explicit call should not be required.
* Updated the "mazerunner" (Spring boot app) end-to-end test to remove the `System.exit` call to test this …
> fix: jvm hangs when System.exit or bugsnag.close is not called

- CONTRIBUTING.md
Added extra instructions for running Mazerunner tests so they aren't missed.
> docs(contributing): add end-to-end test instructions to contributing guide

- README.md
Fixes link to the license file.
> docs(readme): fix broken license file link in readme

- bugsnag-spring/build.gradle
- bugsnag/build.gradle
- build.gradle
- examples/logback/build.gradle
- examples/servlet/build.gradle
- examples/simple/build.gradle
- examples/spring-web/build.gradle
- examples/spring/build.gradle
- features/fixtures/mazerunner/build.gradle
- features/fixtures/mazerunnerplainspring/build.gradle
- features/fixtures/mazerunnerspringboot/build.gradle
- features/fixtures/scenarios/build.gradle
- release.gradle
JCenter has reached end-of-life so mavenCentral should be preferred as a repository. This alters the build scripts of bugsnag-java to avoid using jcenter(), and removes the obsolete bintray publish plugin.
Assembled projects and ran tests locally, also relied on CI.
> Avoid using jcenter() in build scripts

- .buildkite/pipeline.yml
- .travis.yml
- docker-compose.yml
- dockerfiles/Dockerfile.java-common
Migrates our unit tests to Buildkite, which avoids needing to run them on Travis CI.
I've gone for the approach of running the style checks/unit/integration tests against OpenJdk 8 only. I think it makes more sense to run the mazerunner tests against different JDK distributions if we're going to go down that road.
The mazerunner tests will be ported over in a separate changeset.
> Migrate unit tests to buildkite

- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/BugsnagAppender.java
- bugsnag/src/test/java/com/bugsnag/AppenderTest.java
Support error messages that use `{}` formatting in `"Log event data"`.
Added a new unit test to cover formatted messages via an slf4j logger.
> Support formatted log messages

- bugsnag-spring/build.gradle
- build.gradle
- common.gradle
- release.gradle
Enable the command `./gradlew -Preleasing=true publishToMavenLocal` as this was missed when initially upgraded to gradle v7. 
Similar approach to BAGP
Removed the gradle-nexus-plugin and replaced with pom directive.
Prevent release of subprojects spring:javax and spring:jakarta using project.depth
Ensure spring:javax jar exists before packaging bugsnag-spring using 'dependsOn' 
Tested under PLAT-9981
> PIPE-5521: Remove dependency on gradle-nexus-plugin

- CHANGELOG.md
- bugsnag-spring/javax/src/main/java/com/bugsnag/SpringBootJavaxConfiguration.java
- bugsnag/src/main/java/com/bugsnag/callbacks/JavaxServletCallback.java
- bugsnag/src/main/java/com/bugsnag/servlet/BugsnagServletContainerInitializer.java
- bugsnag/src/main/java/com/bugsnag/servlet/BugsnagServletRequestListener.java
- bugsnag/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
- bugsnag/src/test/java/com/bugsnag/JavaxServletCallbackTest.java
Restore the public API for:
- `com.bugsnag.servlet.BugsnagServletContainerInitializer`
- `com.bugsnag.servlet.BugsnagServletRequestListener`
Reintroduced the `com.bugsnag.servlet.BugsnagServletContainerInitializer`, and `com.bugsnag.servlet.BugsnagServletRequestListener` classes as empty sub-classes of `com.bugsnag.servlet.javax.*` so that the migration is clear but existing code will continue to run as-normal.
These "new" `com.bugsnag.servlet.*` classes are marked as `@Deprecated` but are still the classes registered in `META-INF/services`. This means that containers will instantiate these deprecated classes, but that they can be safely downcast to the new `com.bugsnag.servlet.javax` classes.
Any applications that manually register or instantiate the new `com.bugsnag.servlet.javax` …
> Restored the `com.bugsnag.servlet` (javax) classes

- CHANGELOG.md
- CONTRIBUTING.md
- bugsnag-spring/build.gradle
- release.gradle
- Ensure javadocs are generated for `bugsnag-spring`
- Set the Sonatype repo name in the release config
- Add a note about v3.7.0 known issues to changelog 
- Update CONTRIBUTING.md to stage and test releases earlier
> Build script and docs updates

- bugsnag-spring/build.gradle
Make sure that `com.bugsnag:bugsnag-spring` depends on `com.bugsnag:bugsnag` when published. After this PR the `bugsnag-spring.pom` file includes the following dependencies:
```xml
<dependencies>
<dependency>
<groupId>com.bugsnag</groupId>
<artifactId>bugsnag</artifactId>
<version>3.7.0</version>
<scope>compile</scope>
</dependency>
</dependencies>
```
Tested using local publications and manually verifying the contents of the `pom` files.
> bugsnag-spring should depend on bugsnag when published

- CONTRIBUTING.md
- README.md
- Replace references to `master` with `main` in docs (`README.md` and `CONTRIBUTING.md`)
- Update build status badge from Travis CI to Buildkite
> docs: replace references to `master` with `main`

- CHANGELOG.md
- bugsnag-spring/src/common/java/com/bugsnag/BugsnagImportSelector.java
Import selector only accepts versions that have a minor version. Requesting changes [here](https://github.com/bugsnag/bugsnag-java/issues/211)
BugsnagImportselector.java file edited to allow a major version without a minor version which isn't always the case.
Running automated test
> Plat 11507 fix bugsnag import selector

- CHANGELOG.md
- bugsnag/src/main/java/com/bugsnag/Bugsnag.java
- bugsnag/src/main/java/com/bugsnag/Report.java
Null severity causing exception during serialization.
`Cannot invoke "com.bugsnag.Severity.getValue()" because "this.severity" is null`
To check the override for a null severity and log if null = true
Added null check to severity value in the Bugsnag.java class for the notify overwrite method.
Running automated tests.
> Added severity check
